language: node_js
node_js:
  - 4.6
  - 6.9
branches:
  only:
    - master
matrix:
  allow_failures:
    - node_js: 0.10
notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
